export const ADD_FRAGRANCE='ADD_FRAGRANCE';
export const DELETE_FRAGRANCE='DELETE_FRAGRANCE';
export const EDIT_FRAGRANCE='EDIT_FRAGRANCE';
export const ADD_TO_FAVORITES='ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES='REMOVE_FROM_FAVORITES';
export const ADD_TO_CART='ADD_TO_CART';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';
export const SEARCH_BY_SEX='SEARCH_BY_SEX'